notifications:
    email: false

dist: trusty

language: python

python:
    - "2.7"
    - "3.5"

sudo : required

addons:
    apt:
        packages:
            - g++-5

script:
    - python read2aln.py install
    - python read2aln.py demo
