notifications:
    email: false

language: python

python:
    - "2.7"
    - "3.5"

sudo : required
before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get install g++-5

script:
    - python read2aln.py install
    - python read2aln.py demo
