notifications:
    email: false

dist: trusty

language: python

python:
    - "2.7"

sudo : required

addons :
    apt :
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
            - gcc-6

script:
    - python read2aln.py demo
